src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Establishement::class, inversedBy: 'bookings')]
    private $establishement;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'bookings')]
    #[ORM\JoinColumn(onDelete:"CASCADE")]
    private $user;

    #[ORM\ManyToOne(targetEntity: Suite::class, inversedBy: 'bookings')]
    private $suite;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("DateTimeInterface")]
    #[Assert\GreaterThanOrEqual(propertyPath: 'date', message:'La date de debut ne peut être ultérieur à la date d\'aujourdui')]
    private $start;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("DateTimeInterface")]
    #[Assert\GreaterThanOrEqual(propertyPath: 'start', message:'La date de fin ne peut être ultérieur à la date de début')]
    private $end;


    private  $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstablishement(): ?Establishement
    {
        return $this->establishement;
    }

    public function setEstablishement(?Establishement $establishement): self
    {
        $this->establishement = $establishement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSuite(): ?Suite
    {
        return $this->suite;
    }

    public function setSuite(?Suite $suite): self
    {
        $this->suite = $suite;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function __toString()
    {
        return $this->getSuite()->getName();
    }

    public function getDate(): ?\DateTimeInterface {
       $this->date = new DateTime();
        return $this->date;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use Timestampable;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Email(message: 'The email {{ value }} is not a valid email.',)]
    #[Assert\NotBlank()]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    
    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: "please enter a firstName")]
    #[Assert\Length(min: 4, max: 50, minMessage: 'Votre Prénom doit contenir au moin {{ limit }} caractères')]
    private $firstName;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank(message: "please enter a lastName")]
    #[Assert\Length(min: 4, max: 50, minMessage: 'Votre Nom doit contenir au moin {{ limit }} caractères')]
    private $lastName;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Establishement::class, cascade: ['persist','remove'])]
    private $establishement;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Suite::class)]
    private $suites;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Booking::class)]
    private $bookings;

    public function __construct()
    {
        $this->suites = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName()
    {
       return $this->getFirstName().' '.$this->getLastName();
    }

    public function getEstablishement(): ?Establishement
    {
        return $this->establishement;
    }

    public function setEstablishement(Establishement $establishement): self
    {
        // set the owning side of the relation if necessary
        if ($establishement->getUser() !== $this) {
            $establishement->setUser($this);
        }

        $this->establishement = $establishement;

        return $this;
    }

    public function __toString()
    {
        return $this->getFullName();
    }

    /**
     * @return Collection<int, Suite>
     */
    public function getSuites(): Collection
    {
        return $this->suites;
    }

    public function addSuite(Suite $suite): self
    {
        if (!$this->suites->contains($suite)) {
            $this->suites[] = $suite;
            $suite->setUser($this);
        }

        return $this;
    }

    public function removeSuite(Suite $suite): self
    {
        if ($this->suites->removeElement($suite)) {
            // set the owning side to null (unless already changed)
            if ($suite->getUser() === $this) {
                $suite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }

  
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Suite;
use App\Entity\Booking;
use App\Entity\Establishement;
use App\Repository\SuiteRepository;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use App\Repository\EstablishementRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class BookingType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        
        $builder
          
            ->add('establishement', EntityType::class, [
                'class' => Establishement::class,
                'label' => 'Etablissement',
                'choice_label' => function($establishement) {
                    return $establishement->getCity().'- '.$establishement->getName();
                },
                'placeholder' => 'choisissez un etablissement',
                'query_builder' => function(EstablishementRepository $establishementRepo) {
                    return $establishementRepo->createQueryBuilder('e')->orderBy('e.name', 'ASC');
                },
                'constraints' => new NotBlank(['message' => 'Choisissez un etablissement'])
            ])
            ->add('suite', EntityType::class, [
                'class' => Suite::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'bg-light'
                ],
                'disabled' => true,
                'placeholder' => 'Choisissez une suite',
            'query_builder' => function (SuiteRepository $suiteRepo) {
                return $suiteRepo->createQueryBuilder('s')->orderBy('s.name', 'ASC');
            },
            'constraints' => new NotBlank(['message' => 'Choisissez une suite'])
        
            ])
            ->add('start', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de début'
                
            ])
            ->add('end', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de Fin'
            ])

         ;

         $formModifier = function(FormInterface $form, Establishement $establishement = null) {
            $suite = (null === $establishement) ? [] : $establishement->getSuites();

            $form->add('suite', EntityType::class, [
                'class' => Suite::class,
                'choices' => $suite,
                'choice_label' => 'name',
                'placeholder' => 'Suite(Choisissez un etablissement )',
                'label' => 'Suite'
            ]);
         };

         // Listener Establishement
         $builder->get('establishement')->addEventListener(
             FormEvents::POST_SUBMIT,
             function(FormEvent $event) use($formModifier) {
                $establishement = $event->getForm()->getData();
                $formModifier($event->getForm()->getParent(), $establishement);
              }
            );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Suite;
use App\Entity\Booking;
use App\Entity\Establishement;
use App\Form\BookingType;
use App\Repository\SuiteRepository;
use App\Repository\BookingRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\EstablishementRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[Route('/booking')]
#[IsGranted("ROLE_USER")]
class BookingController extends AbstractController
{
    
    #[Route('', name: 'app_booking')]
    public function index(BookingRepository $bookingRepo): Response
    {
        $user = $this->getUser();
        $bookings = $bookingRepo->findBy(['user' => $user]);
        

        return $this->render('booking/index.html.twig', [
            'bookings' => $bookings
        ]);
    }

    #[Route('/{id<[0-9]+>}', name: 'app_booking_show', methods: 'get')]
    public function show(Booking $booking): Response
    {

        return $this->render('booking/show.html.twig', [
            'booking' => $booking
        ]);
    }

    #[Route('/create', name: 'app_booking_create')]
    public function create(Request $request, EntityManagerInterface $em,  EstablishementRepository $establishementRepo, SuiteRepository $suiteRepo): Response
    {
        
        $user = $this->getUser();

        $booking = new Booking;
        $booking->setUser($user);
    
        $form = $this->createForm(BookingType::class,$booking);
        $form->handleRequest($request);
    

        if ($form->isSubmitted() && $form->isValid()) {

            $booking->setUser($user);

            $em->persist($booking);
            $em->flush();

            $this->addFlash('success', 'Réservation effectuée');

            return $this->redirectToRoute('app_home');
        }
        return $this->render('booking/create.html.twig', [
            'form' => $form->createView(),
        
        ]);
    }



    #[Route('delete/{id<[0-9]+>}', name: 'app_booking_delete', methods: 'DELETE')]
    public function delete(Request $request, Booking $booking, EntityManagerInterface $em): RedirectResponse
    { 
                
        $submittedToken = $request->request->get('csrf_token');
        if ($this->isCsrfTokenValid('booking_delete_', $submittedToken)) {

           $em->remove($booking);
            
            $em->flush();

            $this->addFlash('success', 'Votre réservation a bien été annulée');

            return $this->redirectToRoute('app_booking');
        }
    }
    }
    

templates/booking/_delete_form.html.twig
<form id="js-booking-delete-form" action="{{ path('app_booking_delete', {id: booking.id})}}" method="post" style="display:none;">
	<input type="hidden" name="csrf_token" value="{{csrf_token('booking_delete_')}}">
	<input type="hidden" name="_method" value="DELETE">
</form>

templates/booking/_form.html.twig
{{form_start(form)}}

{{form_rest(form)}}
<input type="submit" value="Réserver" class="mt-4 btn btn-info w-100" formnovalidate/>

{{form_end(form)}}

{% block javascript %}
  <script>
    window.onload = () => {
        let establishement = document.querySelector('#booking_establishement');

        establishement.addEventListener("change", function() {
            let form = this.closest('form');
            let data = this.name + "=" + this.value;
            
            fetch(form.action, {
                method: form.getAttribute("method"),
                body: data,
                headers: {
                    "Content-Type":"application/x-www-form-urlencoded;charset:utf8"
                }
            })
            .then(response => response.text())
            .then(html => {
                let content = document.createElement("html");
                content.innerHTML = html;
                let nouveauSelect = content.querySelector('#booking_suite');
                document.querySelector('#booking_suite').replaceWith(nouveauSelect);
            })
        });
    }
  </script>
{% endblock %}

templates/booking/create.html.twig
{% extends "layouts/base.html.twig" %}
{% block title %}Booking -
{% endblock %}


{% block body %}
  <div class="container">
    <h1 class="pt-4 pb-3">Reserver une Suite</h1>
   
    {% include "booking/_form.html.twig" %}
  </div>


{% endblock %}

templates/booking/index.html.twig
{% extends "layouts/base.html.twig" %}
{% block title %}Mes Réservations -
{% endblock %}


{% block body %}
	<div class="container">
	 <div class="col-12 ">
		<h1 class="mt-5 text-center text-info">Mes Réservations</h1>

		<table class="mt-5 mx-auto table table-hover text-center col-12">
			<thead>
				<tr class="table-light">
					<th scope="col">N°</th>
					<th scope="col">Etablissement</th>
					<th scope="col">Debut</th>
					<th scope="col">Fin</th>
					<th scope="col">Details</th>
				</tr>
			</thead>
			<tbody>
				{% for booking in bookings %}
					<tr class="table-primary">
						<td>{{booking.id}}</td>
						<td>{{booking.establishement.name}}</td>
						<td>{{booking.start|date('d-m-Y')}}</td>
						<td>{{booking.end|date('d-m-Y')}}</td>
						<td>
						<a href="{{path('app_booking_show', {id: booking.id})}}">
							<i class="fa-solid fa-plus btn btn-info rounded"></i>
						</a>
						</td>
						</tr>
					{% endfor %}
			</tbody>
		</table>
		<button class="mt-5 btn btn-info btn-sm rounded">
		  <a href="{{path('app_booking_create')}}" class="text-decoration-none text-white">Réserver une suite</a>
		</button>
	</div>
	</div>


{% endblock %}

templates/booking/show.html.twig
{% extends "layouts/base.html.twig" %}
{% block title %}
	{{ booking.establishement.name }}
{% endblock %}

{% block body %}
	<div class="mt-5 container text-center">
		<div class="col-12 mt-4">
			<div class="mx-auto card  border-white  mb-3" style="width:100%">
				<div class="card-header bg-black">
					<h4 class="text-white">Hôtels : <span class="text-info">{{booking.establishement.name}} ★ ★ ★ ★ ★</span></h4>
					<h5 class="text-white">Suite : {{booking.suite.name}}</h5>
				</div>
				<div class="card-body">
					<img src="/uploads/images/suites/{{booking.suite.illustration}}" alt="{{booking.suite.name}}" class=" w-50 "/>
					<p class="card-text mt-3">
                        Lieux:
						<span class="text-info">
                        {{booking.establishement.city}}
                        </span>
						<br>
						Nom de la réservation:
						<span class="text-info">
						{{booking.user.fullName}}
                        </span>
						<br>
						Date de début:
						<span class="text-info">
                        {{booking.start|date('d/m/Y')}}
                        </span>
						<br>
                        Date de fin:
						<span class="text-info">
							{{booking.end|date('d/m/Y')}}
						</span>
						<ul>
							
						</ul>
					</p>

					<div class="ms-3">
						<a href="{{path('app_booking')}}" class="btn btn-sm btn-primary">Retour</a>
						<a href="#" onclick="event.preventDefault(); confirm('Are You sure?')&& document.getElementById('js-booking-delete-form').submit();" class="btn btn-sm btn-info">Annuler la réservation</a>
						{% include "booking/_delete_form.html.twig" %}
					</div>
				</div>
			</div>
		</div>
	</div>


{% endblock %}